/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as usersUsersRouteImport } from './routes/(users)/users'
import { Route as usersInvitationsRouteImport } from './routes/(users)/invitations'
import { Route as mediaMediaRouteImport } from './routes/(media)/media'
import { Route as contentNotificationsRouteImport } from './routes/(content)/notifications'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as databasesrolesRolesRouteImport } from './routes/(databases)/(roles)/roles'
import { Route as databasespermissionsPermissionsRouteImport } from './routes/(databases)/(permissions)/permissions'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const usersUsersRoute = usersUsersRouteImport.update({
  id: '/(users)/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const usersInvitationsRoute = usersInvitationsRouteImport.update({
  id: '/(users)/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const mediaMediaRoute = mediaMediaRouteImport.update({
  id: '/(media)/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const contentNotificationsRoute = contentNotificationsRouteImport.update({
  id: '/(content)/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/(auth)/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const databasesrolesRolesRoute = databasesrolesRolesRouteImport.update({
  id: '/(databases)/(roles)/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const databasespermissionsPermissionsRoute =
  databasespermissionsPermissionsRouteImport.update({
    id: '/(databases)/(permissions)/permissions',
    path: '/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/notifications': typeof contentNotificationsRoute
  '/media': typeof mediaMediaRoute
  '/invitations': typeof usersInvitationsRoute
  '/users': typeof usersUsersRoute
  '/permissions': typeof databasespermissionsPermissionsRoute
  '/roles': typeof databasesrolesRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/notifications': typeof contentNotificationsRoute
  '/media': typeof mediaMediaRoute
  '/invitations': typeof usersInvitationsRoute
  '/users': typeof usersUsersRoute
  '/permissions': typeof databasespermissionsPermissionsRoute
  '/roles': typeof databasesrolesRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(content)/notifications': typeof contentNotificationsRoute
  '/(media)/media': typeof mediaMediaRoute
  '/(users)/invitations': typeof usersInvitationsRoute
  '/(users)/users': typeof usersUsersRoute
  '/(databases)/(permissions)/permissions': typeof databasespermissionsPermissionsRoute
  '/(databases)/(roles)/roles': typeof databasesrolesRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/notifications'
    | '/media'
    | '/invitations'
    | '/users'
    | '/permissions'
    | '/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/notifications'
    | '/media'
    | '/invitations'
    | '/users'
    | '/permissions'
    | '/roles'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/settings'
    | '/todos'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(content)/notifications'
    | '/(media)/media'
    | '/(users)/invitations'
    | '/(users)/users'
    | '/(databases)/(permissions)/permissions'
    | '/(databases)/(roles)/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TodosRoute: typeof TodosRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  contentNotificationsRoute: typeof contentNotificationsRoute
  mediaMediaRoute: typeof mediaMediaRoute
  usersInvitationsRoute: typeof usersInvitationsRoute
  usersUsersRoute: typeof usersUsersRoute
  databasespermissionsPermissionsRoute: typeof databasespermissionsPermissionsRoute
  databasesrolesRolesRoute: typeof databasesrolesRolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(users)/users': {
      id: '/(users)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof usersUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(users)/invitations': {
      id: '/(users)/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof usersInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(media)/media': {
      id: '/(media)/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof mediaMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content)/notifications': {
      id: '/(content)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof contentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(databases)/(roles)/roles': {
      id: '/(databases)/(roles)/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof databasesrolesRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(databases)/(permissions)/permissions': {
      id: '/(databases)/(permissions)/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof databasespermissionsPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TodosRoute: TodosRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  contentNotificationsRoute: contentNotificationsRoute,
  mediaMediaRoute: mediaMediaRoute,
  usersInvitationsRoute: usersInvitationsRoute,
  usersUsersRoute: usersUsersRoute,
  databasespermissionsPermissionsRoute: databasespermissionsPermissionsRoute,
  databasesrolesRolesRoute: databasesrolesRolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
